name: Chocolate OS
id: chocolate-os
vibversion: 1.0.1
stages:
  - id: build
    base: ghcr.io/vanilla-os/core:main
    singlelayer: false
    addincludes: true
    labels:
      maintainer: Tichael
    args:
      DEBIAN_FRONTEND: noninteractive
    
    runs:
      commands:
        - echo 'APT::Install-Recommends "0";' > /etc/apt/apt.conf.d/01norecommends
        - echo 'APT::Install-Suggests "0";' >> /etc/apt/apt.conf.d/01norecommends

    modules:
    - name: init-setup
      type: shell
      commands:
        - echo 'PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"' > /etc/environment
        - sed -i '4,10d' /etc/profile # Remove the lines that setup the PATH, since we do it just above.
        - apt update
        - apt upgrade -y
        - apt -y install squashfs-tools minisign
        - apt-mark hold snapd
        - apt clean

    - name: vanilla-tools
      type: shell
      sources:
        - type: tar
          url: https://github.com/Vanilla-OS/vanilla-tools/releases/download/v1.0.0/vanilla-tools.tar.gz
          checksum: 0e1d92d9c9154f9a115e97b40ff692afa52ddd0d9f770a8ec67440bf1a48aa72
      commands:
        - mkdir -p /usr/bin
        - cp /sources/vanilla-tools/vanilla-tools/vanilla-tools/lpkg /usr/bin/lpkg
        - chmod +x /usr/bin/lpkg

    # Run customization modules here
    - name: packages-modules
      type: includes
      includes:
        - modules/00-vanilla-system-operator.yml
        - modules/03-fswarn.yml
        - modules/50-install-debs.yml
        - modules/80-set-image-abroot-config.yml
        - modules/997-ensure-exec-hooks.yml
        - modules/999-sudont.yml

    - name: cleanup
      type: shell
      commands:
        - apt-get autoremove -y
        - apt-get clean
        - lpkg --lock

    - name: sysconf-setup
      type: shell
      commands:
        - rsync -a /etc/ /sysconf/

    - name: fsguard
      type: fsguard
      CustomFsGuard: false
      FsGuardLocation: "/usr/sbin/FsGuard"
      GenerateKey: true
      FilelistPaths: ["/usr/bin"]
      modules:
        - name: remove-prev-fsguard
          type: shell
          commands:
            - rm -rf /FsGuard 
            - rm -f ./minisign.pub ./minisign.key 
            - chmod +x /usr/sbin/init

    - name: cleanup2
      type: shell
      commands:
        - rm -rf /tmp/*
        - rm -rf /var/tmp/*
        - rm -rf /sources
